version: '3.8'
services:
  nginx:
    image: marublaize/nginx-bullseye-slim:latest
    restart: always
    ports:
      - '80:80'
    volumes: 
      - ./html:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/nginx.conf